version: '3'

services:
  nginx: #服务名称
    image: nginx:latest
    ports:
      - 3304:80
    volumes:
      - /root/nginx/html:/usr/share/nginx/html
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
    # 解决nginx的文件调用的权限问题

  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  rjwm:
    image: rjwm:latest
    build: .
    ports:
      - 8082:8082
    depends_on:
      - mysql
      -